import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';

export const metadata = {
  title: 'Terms of Service · CvClimber',
  description: 'Terms of Service for CvClimber — AI-powered CV analysis and job search platform.',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen text-white" style={{ background: '#0a0d24' }}>
      <section className="relative overflow-hidden" style={{ paddingTop: '120px', paddingBottom: '40px' }}>
        <div className="absolute inset-0" style={{ backgroundImage: 'url(/aivent/background/3.webp)', backgroundSize: 'cover', backgroundPosition: 'center' }} />
        <div className="absolute inset-0" style={{ background: 'rgba(8,11,32,0.85)' }} />
        <div className="absolute bottom-0 left-0 right-0" style={{ height: '50%', background: 'linear-gradient(0deg,#0a0d24 0%,transparent 100%)' }} />
        <div className="relative mx-auto max-w-4xl px-6" style={{ zIndex: 2 }}>
          <Link href="/" className="inline-flex items-center gap-2 text-white/30 hover:text-white/60 text-xs font-semibold uppercase tracking-widest mb-6 transition-colors">
            <ArrowLeft className="h-3.5 w-3.5" /> Back to Home
          </Link>
          <h1 className="text-white leading-[1.05]" style={{ fontSize: 'clamp(36px,5vw,64px)', fontWeight: 800, letterSpacing: '-0.03em' }}>
            Terms of Service
          </h1>
          <p className="text-white/45 text-sm mt-4">Last updated: April 29, 2026</p>
        </div>
      </section>

      <section className="px-6 pb-24">
        <div className="mx-auto max-w-3xl space-y-8 text-white/70 text-base leading-relaxed">

          <div>
            <h2 className="text-white text-2xl font-bold mb-3">1. Acceptance of Terms</h2>
            <p>By accessing or using CvClimber (the "Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree, please do not use the Service.</p>
          </div>

          <div>
            <h2 className="text-white text-2xl font-bold mb-3">2. Description of Service</h2>
            <p>CvClimber is an AI-powered web application that provides CV/resume analysis, ATS scoring, keyword gap reports, AI-generated cover letters, a job application tracker, CV history and analytics, and (on Pro+ plans) AI voice mock-interview coaching plus the multi-source Job Hunter job aggregator.</p>
          </div>

          <div>
            <h2 className="text-white text-2xl font-bold mb-3">3. Accounts</h2>
            <p>To use most features you must create an account with a valid email address. You are responsible for maintaining the confidentiality of your credentials and for all activity under your account. You must be at least 16 years old to use the Service.</p>
          </div>

          <div>
            <h2 className="text-white text-2xl font-bold mb-3">4. Plans, Billing & Auto-Renewal</h2>
            <p>CvClimber offers a Free plan, a one-time 7-Day Pass ($9, no auto-renewal), and recurring subscriptions (Pro $19/month or $149/year, Pro+ $39/month or $299/year). Subscriptions automatically renew at the end of each billing cycle until cancelled. Payments are processed by Lemon Squeezy, our authorized reseller and Merchant of Record.</p>
          </div>

          <div>
            <h2 className="text-white text-2xl font-bold mb-3">5. Cancellation</h2>
            <p>You may cancel a recurring subscription at any time from your account settings or by contacting support. Cancellation takes effect at the end of the current billing period; you keep access until then.</p>
          </div>

          <div>
            <h2 className="text-white text-2xl font-bold mb-3">6. Acceptable Use</h2>
            <p>You agree not to: (a) use the Service for any unlawful purpose; (b) upload content that is illegal, infringing, defamatory, or contains malware; (c) attempt to reverse-engineer, scrape, or interfere with the Service; (d) resell or redistribute AI-generated outputs as a competing service; (e) submit another person's CV without their permission.</p>
          </div>

          <div>
            <h2 className="text-white text-2xl font-bold mb-3">7. AI Output Disclaimer</h2>
            <p>CV analyses, ATS scores, cover letters, and interview feedback are generated by AI and provided "as is" for guidance only. CvClimber does not guarantee any job interview, offer, or employment outcome.</p>
          </div>

          <div>
            <h2 className="text-white text-2xl font-bold mb-3">8. Intellectual Property</h2>
            <p>The Service, its design, logos, and software are owned by CvClimber and protected by intellectual property laws. You retain ownership of the CV content you upload. You grant us a limited license to process that content solely to provide the Service.</p>
          </div>

          <div>
            <h2 className="text-white text-2xl font-bold mb-3">9. Termination</h2>
            <p>We may suspend or terminate your account if you breach these Terms or use the Service in a way that harms us or other users. You may delete your account at any time from your settings.</p>
          </div>

          <div>
            <h2 className="text-white text-2xl font-bold mb-3">10. Limitation of Liability</h2>
            <p>To the maximum extent permitted by law, CvClimber and its affiliates are not liable for indirect, incidental, special, or consequential damages arising from your use of the Service. Our total liability is limited to the amount you paid us in the 12 months preceding the claim.</p>
          </div>

          <div>
            <h2 className="text-white text-2xl font-bold mb-3">11. Changes to These Terms</h2>
            <p>We may update these Terms from time to time. Material changes will be announced by email or in-app notice. Continued use of the Service after changes take effect constitutes acceptance.</p>
          </div>

          <div>
            <h2 className="text-white text-2xl font-bold mb-3">12. Governing Law</h2>
            <p>These Terms are governed by the laws of the jurisdiction where CvClimber is established, without regard to conflict-of-law rules. Disputes will be resolved in the competent courts of that jurisdiction.</p>
          </div>

          <div>
            <h2 className="text-white text-2xl font-bold mb-3">13. Contact</h2>
            <p>Questions about these Terms? Reach us at <Link href="/contact" className="text-purple-400 hover:text-purple-300 underline">our contact page</Link> or via support@cvclimber.lol.</p>
          </div>

        </div>
      </section>
    </div>
  );
}
